### ISSUE TITLE
What would a good function name/code be for hypervisor servers (VMware ESXi, Hyper-V, etc)?

### ISSUE THREAD

**Issue by mclarty** [defendthehoneypot/NamingConvention#2]

**Comment by defendthehoneypot** [comment]
I generally use VM if its a guest operating system.  Are you asking about the underlying hardware system?

**Comment by mclarty** [comment]
Yep, the physical host server (like the individual VMware ESXi servers, the vCenter management server, etc).

**Comment by defendthehoneypot** [comment]
For VMWare hosts I use "ESXI" in the name. Never had to name Hyper-V hosts.  As an example "xyzesxisac01"
